language: python

python:
  - 3.5

install: 
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  py.test --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls
